Vagrant.configure("2") do |config|
  config.vm.box = "hfeng/ubuntu1604"
  config.vm.provider 'virtualbox' do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    vb.memory = '16384'
    vb.cpus = 4
  end
end
